language: java
notifications:
  email: false
before_install: chmod +x gradlew
install: ./gradlew setupCIWorkspace -S
matrix:
  include:
  - jdk: oraclejdk7
    script: mvn clean package
  - jdk: oraclejdk7
    script: ./gradlew build -S