language: java
notifications:
  email: false
before_install: chmod +x gradlew
install: ./gradlew setupCIWorkspace -s
script: ./gradlew build -s
jdk:
  - oraclejdk8
# Caching for Gradle files, prevents hitting Maven too much.
before_cache:
  - find $HOME/.gradle/ -name '*.lock' -print -exec rm -f {} \;
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Faster builds without sudo.
sudo: false
